[package]
name = "binary-serialize-derive"
authors = ["Rintaro Itokawa <me@re-taro.dev>"]
version = "0.0.0"
edition = "2021"
repository = "https://github.com/re-taro/decaf"

[dependencies]
syn-helpers = "0.5"

[lib]
path = "macro.rs"
proc-macro = true
